# Use R
language: r
cache: packages
warnings_are_errors: false
# environment variables set for all builds
env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"  ## do not build vignettes or manual
    - _R_CHECK_TIMINGS_="0"  ## get the timing information for the examples for all of your functions

os:
  - linux

# do not build vignettes...takes too long and times out on travis
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings

# for codecov
r_packages:
  - covr

jobs:
  include:
  - r: release
    r_github_packages: r-lib/usethis
  - r: devel
    r_github_packages: r-lib/usethis
  - r: release
  - r: devel
  allow_failures:
  - r: release
    r_github_packages:
  - r: devel
    r_github_packages:

# only report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
